### ISSUE TITLE
Multiple wild cards and filters

### ISSUE THREAD

**Issue by sharathsridhar** [sripathikrishnan/jinjasql#35]
Hello, Thank you for a great library. I am looking to build a complex sql query which has multiple wild card statements, for example
`Select * From table A
Where (A.col1 like '%abc%'
or A.col1 like '%123%'
or A.col1 like '%345%')
AND (B.col2 like '%xyz%'
or B.col2 like '%qwe%')...`
etc., where the values within the wildcards are in a list or dictionary. Is this possible?

**Comment by clayadavis** [comment]
This is a good usecase for the Jinja syntax. In the Python, you'd have something like
```python
data = {
    'col1_patterns': ['%abc%', '%123%', '%345%'],
    'col2_patterns': ['%xyz%', '%qwe'],
}
```
and in the template:
```jinja2
SELECT * FROM table A
WHERE (
{%- for pattern in col1_patterns %}
    A.col1 like {{ pattern }}
    {% if not loop.last %} or {% endif -%}
{% endfor -%}
)
AND (
{%- for pattern in col2_patterns %}
    A.col2 like {{ pattern }}
    {% if not loop.last %} or {% endif -%}
{% endfor -%}
)
```

More info on [Jinja template design](https://jinja.palletsprojects.com/en/2.11.x/templates/), specifically:
* [loop variables](https://jinja.palletsprojects.com/en/2.11.x/templates/#for) like the `loop.last`,
* and [whitespace control](https://jinja.palletsprojects.com/en/2.11.x/templates/#whitespace-control) for those extra dashes `{%-` and `-%}`.
* You could get fancy and make a [template macro](https://jinja.palletsprojects.com/en/2.11.x/templates/#macros) for this if you wanted.
