### ISSUE TITLE
sqlsafe not compatible with sqlfluff

### ISSUE THREAD

**Issue by david-walker-gfs** [sripathikrishnan/jinjasql#41]
Really like this package. However I've stumbled upon an issue. I'm trying to create queries for dynamic tables and have to use the sqlsafe filter to do so. However, sqlfluff is then complaing that it cannot find the filter. Perhaps there's a way around this? 

```
Failure to parse jinja template: no filter named 'sqlsafe'
```

Sample bigquery query that generates this issue for me
```
SELECT *
FROM `{{ project | sqlsafe }}.{{ dataset | sqlsafe }}.{{ table | sqlsafe }}`
```

**Comment by sripathikrishnan** [comment]
This is outside the scope of JinjaSQL. 

From what I understand, Sqlfluff was designed for Jinja2 templates. JinjaSQL is an extension on top of Jinja2, and adds the sqlsafe parameter which Jinja2 does not have. As a result, Sqlfluff complains about this filter.

Unfortunately, this is something that sqlfluff would have to implement.
