### ISSUE TITLE
[Feature request] Single function with outputting the full query with parameters

### ISSUE THREAD

**Issue by kishaningithub** [sripathikrishnan/jinjasql#46]
## Usecase

Using python i am writing an aws lambda which interacts with redshift data api especially the BatchExecuteStatement operation. If you observe this api takes in list of SQL queries without any params.. meaning that the query should also have parameters within it as a single string

- https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/redshift-data.html#RedshiftDataAPIService.Client.batch_execute_statement
- https://docs.aws.amazon.com/redshift-data/latest/APIReference/API_BatchExecuteStatement.html

**Comment by sripathikrishnan** [comment]
I don't think this makes sense in JinjaSQL right now. Different databases have different escape functions, and at this point - I am not sure if we should complicate JinjaSQL. 

You can achieve this outside of JinjaSQL fairly easily. For example, if you are using psycopg library for postgres/redshift, it exposes a [mogrify function](https://www.psycopg.org/docs/cursor.html#cursor.mogrify). You take the output of prepare_query and pass it to mogrify, and you should get the full query.

**Comment by kishaningithub** [comment]
I agree mapping the params to appropriate sql column types is a database dependent operation and would be too much for this library.

Closing this issue..

Also, not all libs and apis(looking at redshiftdata api) provide a mogrify function :-(
